engines:
  eslint:
    enabled: true
    channel: 'eslint-8'
    config:
      config: '.eslintrc.yaml'

checks:
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  method-complexity:
    config:
      threshold: 15
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 50

ratings:
  paths:
    - '**.js'
